export const PLAYERLEVELUP = 'PLAYERLEVELUP';




export const CHANGE_HUD_HOVER_MESSAGE = 'CHANGE_HUD_HOVER_MESSAGE';
export const REVERT_HUD_HOVER_MESSAGE = 'REVERT_HUD_HOVER_MESSAGE';




export const MAPGENERATE = 'MAPGENERATE';

export const PLAYER_MOVE_Y = 'PLAYER_MOVE_Y';
export const PLAYER_MOVE_X = 'PLAYER_MOVE_X';

export const PLAYER_REGEN = 'PLAYER_REGEN';


export const PLAYER_UPDATE_STATS = 'PLAYER_UPDATE_STATS';
export const PLAYER_TOUCHED_ALTAR = 'PLAYER_TOUCHED_ALTAR';
export const PLAYER_TOUCHED_GOLD = 'PLAYER_TOUCHED_GOLD';
export const PLAYER_ATTACKS_MOB = 'PLAYER_ATTACKS_MOB';

export const PLAYER_LEVEL_UP = 'PLAYER_LEVEL_UP';